/** NSE / BSE F&O equity → sector map (desk taxonomy aligned to Nifty sectoral families). */
export const SECTORS = [
  "Banks",
  "Financial Services",
  "IT",
  "Pharma & Healthcare",
  "Automobile",
  "FMCG",
  "Metals & Mining",
  "Oil Gas & Energy",
  "Power & Utilities",
  "Realty",
  "Telecom & Media",
  "Capital Goods & Infra",
  "Chemicals",
  "Consumer Durables",
  "Aviation & Logistics",
  "Defence & PSU",
  "Others",
] as const;

export type Sector = (typeof SECTORS)[number];

const RAW: Record<string, Sector> = {
  // Banks
  AXISBANK: "Banks",
  BANDHANBNK: "Banks",
  BANKBARODA: "Banks",
  BANKINDIA: "Banks",
  CANBK: "Banks",
  FEDERALBNK: "Banks",
  HDFCBANK: "Banks",
  ICICIBANK: "Banks",
  IDFCFIRSTB: "Banks",
  INDUSINDBK: "Banks",
  INDIANB: "Banks",
  KOTAKBANK: "Banks",
  PNB: "Banks",
  RBLBANK: "Banks",
  SBIN: "Banks",
  UNIONBANK: "Banks",
  YESBANK: "Banks",
  AUBANK: "Banks",

  // Financial Services
  "360ONE": "Financial Services",
  ABCAPITAL: "Financial Services",
  ANGELONE: "Financial Services",
  BAJAJFINSV: "Financial Services",
  BAJAJHLDNG: "Financial Services",
  BAJFINANCE: "Financial Services",
  BSE: "Financial Services",
  CAMS: "Financial Services",
  CDSL: "Financial Services",
  CHOLAFIN: "Financial Services",
  HDFCAMC: "Financial Services",
  HDFCLIFE: "Financial Services",
  ICICIGI: "Financial Services",
  ICICIPRULI: "Financial Services",
  IEX: "Financial Services",
  JIOFIN: "Financial Services",
  KFINTECH: "Financial Services",
  LICHSGFIN: "Financial Services",
  LICI: "Financial Services",
  LTF: "Financial Services",
  MANAPPURAM: "Financial Services",
  MCX: "Financial Services",
  MFSL: "Financial Services",
  MOTILALOFS: "Financial Services",
  MUTHOOTFIN: "Financial Services",
  "NAM-INDIA": "Financial Services",
  NUVAMA: "Financial Services",
  PAYTM: "Financial Services",
  PFC: "Financial Services",
  PNBHOUSING: "Financial Services",
  POLICYBZR: "Financial Services",
  RECLTD: "Financial Services",
  SBICARD: "Financial Services",
  SBILIFE: "Financial Services",
  SHRIRAMFIN: "Financial Services",
  IRFC: "Financial Services",
  IREDA: "Financial Services",

  // IT
  COFORGE: "IT",
  HCLTECH: "IT",
  INFY: "IT",
  KPITTECH: "IT",
  LTM: "IT",
  MPHASIS: "IT",
  NAUKRI: "IT",
  OFSS: "IT",
  PERSISTENT: "IT",
  TATAELXSI: "IT",
  TCS: "IT",
  TECHM: "IT",
  WIPRO: "IT",
  KAYNES: "IT",
  DIXON: "IT",
  PGEL: "IT",

  // Pharma & Healthcare
  ALKEM: "Pharma & Healthcare",
  APOLLOHOSP: "Pharma & Healthcare",
  AUROPHARMA: "Pharma & Healthcare",
  BIOCON: "Pharma & Healthcare",
  CIPLA: "Pharma & Healthcare",
  DIVISLAB: "Pharma & Healthcare",
  DRREDDY: "Pharma & Healthcare",
  FORTIS: "Pharma & Healthcare",
  GLENMARK: "Pharma & Healthcare",
  LAURUSLABS: "Pharma & Healthcare",
  LUPIN: "Pharma & Healthcare",
  MANKIND: "Pharma & Healthcare",
  MAXHEALTH: "Pharma & Healthcare",
  SUNPHARMA: "Pharma & Healthcare",
  TORNTPHARM: "Pharma & Healthcare",
  ZYDUSLIFE: "Pharma & Healthcare",

  // Automobile
  ASHOKLEY: "Automobile",
  "BAJAJ-AUTO": "Automobile",
  BHARATFORG: "Automobile",
  BOSCHLTD: "Automobile",
  EICHERMOT: "Automobile",
  EXIDEIND: "Automobile",
  FORCEMOT: "Automobile",
  HEROMOTOCO: "Automobile",
  HYUNDAI: "Automobile",
  "M&M": "Automobile",
  MARUTI: "Automobile",
  MOTHERSON: "Automobile",
  SONACOMS: "Automobile",
  TIINDIA: "Automobile",
  TMPV: "Automobile",
  TVSMOTOR: "Automobile",
  UNOMINDA: "Automobile",

  // FMCG
  BRITANNIA: "FMCG",
  COLPAL: "FMCG",
  DABUR: "FMCG",
  GODFRYPHLP: "FMCG",
  GODREJCP: "FMCG",
  HINDUNILVR: "FMCG",
  ITC: "FMCG",
  JUBLFOOD: "FMCG",
  MARICO: "FMCG",
  NESTLEIND: "FMCG",
  PATANJALI: "FMCG",
  RADICO: "FMCG",
  TATACONSUM: "FMCG",
  UNITDSPR: "FMCG",
  VBL: "FMCG",
  VMM: "FMCG",
  NYKAA: "FMCG",
  PAGEIND: "FMCG",
  DMART: "FMCG",
  TRENT: "FMCG",
  SWIGGY: "FMCG",
  ETERNAL: "FMCG",

  // Metals & Mining
  COALINDIA: "Metals & Mining",
  HINDALCO: "Metals & Mining",
  HINDZINC: "Metals & Mining",
  JINDALSTEL: "Metals & Mining",
  JSWSTEEL: "Metals & Mining",
  NATIONALUM: "Metals & Mining",
  NMDC: "Metals & Mining",
  SAIL: "Metals & Mining",
  TATASTEEL: "Metals & Mining",
  VEDL: "Metals & Mining",
  APLAPOLLO: "Metals & Mining",

  // Oil Gas & Energy
  BPCL: "Oil Gas & Energy",
  GAIL: "Oil Gas & Energy",
  HINDPETRO: "Oil Gas & Energy",
  IOC: "Oil Gas & Energy",
  OIL: "Oil Gas & Energy",
  ONGC: "Oil Gas & Energy",
  PETRONET: "Oil Gas & Energy",
  RELIANCE: "Oil Gas & Energy",

  // Power & Utilities
  ADANIENSOL: "Power & Utilities",
  ADANIGREEN: "Power & Utilities",
  ADANIPOWER: "Power & Utilities",
  JSWENERGY: "Power & Utilities",
  NHPC: "Power & Utilities",
  NTPC: "Power & Utilities",
  POWERGRID: "Power & Utilities",
  PREMIERENE: "Power & Utilities",
  SUZLON: "Power & Utilities",
  TATAPOWER: "Power & Utilities",
  INOXWIND: "Power & Utilities",
  WAAREEENER: "Power & Utilities",

  // Realty
  DLF: "Realty",
  GODREJPROP: "Realty",
  LODHA: "Realty",
  NBCC: "Realty",
  OBEROIRLTY: "Realty",
  PHOENIXLTD: "Realty",
  PRESTIGE: "Realty",

  // Telecom & Media
  BHARTIARTL: "Telecom & Media",
  IDEA: "Telecom & Media",
  INDUSTOWER: "Telecom & Media",

  // Capital Goods & Infra
  ABB: "Capital Goods & Infra",
  ADANIENT: "Capital Goods & Infra",
  ADANIPORTS: "Capital Goods & Infra",
  AMBER: "Capital Goods & Infra",
  AMBUJACEM: "Capital Goods & Infra",
  ASTRAL: "Capital Goods & Infra",
  BEL: "Capital Goods & Infra",
  BHEL: "Capital Goods & Infra",
  BLUESTARCO: "Capital Goods & Infra",
  CGPOWER: "Capital Goods & Infra",
  CONCOR: "Capital Goods & Infra",
  CROMPTON: "Capital Goods & Infra",
  CUMMINSIND: "Capital Goods & Infra",
  DALBHARAT: "Capital Goods & Infra",
  GRASIM: "Capital Goods & Infra",
  "GVT&D": "Capital Goods & Infra",
  HAVELLS: "Capital Goods & Infra",
  KEI: "Capital Goods & Infra",
  LT: "Capital Goods & Infra",
  POLYCAB: "Capital Goods & Infra",
  POWERINDIA: "Capital Goods & Infra",
  RVNL: "Capital Goods & Infra",
  SHREECEM: "Capital Goods & Infra",
  SIEMENS: "Capital Goods & Infra",
  SUPREMEIND: "Capital Goods & Infra",
  ULTRACEMCO: "Capital Goods & Infra",
  VOLTAS: "Capital Goods & Infra",

  // Chemicals
  PIDILITIND: "Chemicals",
  PIIND: "Chemicals",
  SOLARINDS: "Chemicals",
  SRF: "Chemicals",
  UPL: "Chemicals",

  // Consumer Durables
  ASIANPAINT: "Consumer Durables",
  KALYANKJIL: "Consumer Durables",
  TITAN: "Consumer Durables",

  // Aviation & Logistics
  DELHIVERY: "Aviation & Logistics",
  GMRAIRPORT: "Aviation & Logistics",
  INDIGO: "Aviation & Logistics",
  INDHOTEL: "Aviation & Logistics",

  // Defence & PSU
  BDL: "Defence & PSU",
  COCHINSHIP: "Defence & PSU",
  HAL: "Defence & PSU",
  MAZDOCK: "Defence & PSU",
};

export function sectorForSymbol(symbol: string): Sector {
  return RAW[symbol.toUpperCase()] ?? "Others";
}

export function groupSymbolsBySector(symbols: string[]): Record<Sector, string[]> {
  const groups = {} as Record<Sector, string[]>;
  for (const sector of SECTORS) groups[sector] = [];
  for (const symbol of symbols) {
    groups[sectorForSymbol(symbol)].push(symbol);
  }
  for (const sector of SECTORS) groups[sector].sort();
  return groups;
}
